name: Build PDFs

on:
  push:
    paths:
      - docs/*.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc and other dependencies
        run: sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra

      - name: Convert markdown to pdf
        run: |
          mkdir dist
          for file in docs/*.md; do
            pandoc "$file" -o "dist/$(basename "$file" .md).pdf"
          done
        
      - name: Zip pdf files
        run: |
          echo "$(pwd)"
          zip -rv pdfs.zip dist/
        
      - name: Artifact check
        run: |
          outpath="$(pwd)/pdfs.zip"
          if [ -f "$outpath" ]; then
            echo "$outpath exists, and everything is good"
            exit 0
          else
            echo "cannot locate artifacts at $outpath. exiting..."
            exit 1
          fi

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs.zip
