name: Build PDFs

on:
  push:
    paths:
      - docs/*.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc and other dependencies
        run: sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra

      - name: Convert markdown to pdf
        run: |
          mkdir dist
          if [ -d "docs/assets" ]; then
            cd docs
            for file in *.md; do
              pandoc "$file" -o "../dist/$(basename "$file" .md).pdf"
            done
            cd ..
          else
            for file in docs/*.md; do
              pandoc "$file" -o "dist/$(basename "$file" .md).pdf"
            done
          fi
        
      - name: Zip pdf files
        run: |
          echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | rev | cut -d/ -f1 | rev)" >> $GITHUB_ENV
          zip -rv "$(echo $GITHUB_REPOSITORY | rev | cut -d/ -f1 | rev).zip" dist/
        
      - name: Artifact check
        run: |
          outpath="$(pwd)/${{ env.REPO_NAME }}.zip"
          if [ -f "$outpath" ]; then
            echo "$outpath exists, and everything is good"
            exit 0
          else
            echo "cannot locate artifacts at $outpath. exiting..."
            exit 1
          fi
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ${{ env.REPO_NAME }}.zip
