on:
  push:
    branches: [main]
  release:
    types: [published]

name: to-pdf
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Markdown to PDF
        run: |
          # Install pandoc and LaTeX
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-xetex
          # Convert all .md files in the repository to .pdf
          find . -name "*.md" -exec pandoc --pdf-engine=xelatex {} -o {}.pdf \;
      - uses: actions/create-release@v1
        name: Upload PDF to Releases
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
